name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SourceRevisionId: ${{ github.sha }}
  Configuration: "Release"


jobs:
  build_unittest:
    name: Build and unit test
    runs-on: ubuntu-latest
    env:
      DOTNET_INSTALL_DIR: .temp/dotnet
      DOTNET_ROOT: .temp/dotnet
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: dotnet --info
      run:  dotnet --info
    - name: Restore dependencies
      run: dotnet restore
    - name: Check format
      run: dotnet format whitespace --no-restore --verify-no-changes --verbosity detailed && dotnet format style --no-restore --verify-no-changes --verbosity n
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName!~FunctionalTests
    - name: Pack
      run: dotnet pack --no-build --verbosity normal
    - name: Upload nupkg artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-subset-nupkg-artifact
        retention-days: "15"
        if-no-files-found: error
        path: |
          artifacts/${{ env.Configuration }}/nupkg/dotnet-subset/dotnet-subset.*.nupkg
    - name: Upload tests artifact
      uses: actions/upload-artifact@v3
      with:
        name: job-tests-artifact
        retention-days: "1"
        if-no-files-found: error
        path: |
          artifacts/${{ env.Configuration }}/bin/

  functional_tests:
    name: Run functional test
    needs: [build_unittest]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: [ '6.0.x', '7.0.x' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: dotnet --info
      run:  dotnet --info
    - uses: actions/download-artifact@v3
      with:
        name: dotnet-subset-nupkg-artifact
        path: artifacts/${{ env.Configuration }}/nupkg/dotnet-subset
    - uses: actions/download-artifact@v3
      with:
        name: job-tests-artifact
        path: artifacts/${{ env.Configuration }}
    - name: Install dotnet-subset
      env:
        http_proxy: "http://localhost:15937" # Random proxy
        NUGET_ENABLE_ENHANCED_HTTP_RETRY: "false"
      run:  dotnet tool install dotnet-subset --global --verbosity normal --ignore-failed-sources --add-source ./artifacts/${{ env.Configuration }}/nupkg/dotnet-subset/
    - name: Show dotnet-subset version
      run: dotnet subset --version
    - name: Functional Tests
      env:
        CI_DOTNET_SUBSET_TEST_RESOURCES_DIR: ${{ github.workspace }}/test/_resources
      run: dotnet test "artifacts\**\*Tests.dll" --verbosity normal --filter FullyQualifiedName~FunctionalTests
